/* tslint:disable */
/* eslint-disable */
/**
 * Lazzer Beam
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrorDetail
 */
export interface ErrorDetail {
    /**
     * Where the error occurred, e.g. \'body.items[3].tags\' or \'path.thing-id\'
     * @type {string}
     * @memberof ErrorDetail
     */
    'location'?: string;
    /**
     * Error message text
     * @type {string}
     * @memberof ErrorDetail
     */
    'message'?: string;
    /**
     * 
     * @type {any}
     * @memberof ErrorDetail
     */
    'value'?: any;
}
/**
 * 
 * @export
 * @interface ErrorModel
 */
export interface ErrorModel {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ErrorModel
     */
    '$schema'?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof ErrorModel
     */
    'detail'?: string;
    /**
     * Optional list of individual error details
     * @type {Array<ErrorDetail>}
     * @memberof ErrorModel
     */
    'errors'?: Array<ErrorDetail>;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * @type {string}
     * @memberof ErrorModel
     */
    'instance'?: string;
    /**
     * HTTP status code
     * @type {number}
     * @memberof ErrorModel
     */
    'status'?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     * @type {string}
     * @memberof ErrorModel
     */
    'title'?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     * @type {string}
     * @memberof ErrorModel
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface HomeGetOutputBody
 */
export interface HomeGetOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof HomeGetOutputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {string}
     * @memberof HomeGetOutputBody
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    'email': string;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface ProfileGetOutputBody
 */
export interface ProfileGetOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ProfileGetOutputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {Profile}
     * @memberof ProfileGetOutputBody
     */
    'object': Profile;
}
/**
 * 
 * @export
 * @interface ProfileUpdate
 */
export interface ProfileUpdate {
    /**
     * 
     * @type {number}
     * @memberof ProfileUpdate
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdate
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface ProfileUpdateEmail
 */
export interface ProfileUpdateEmail {
    /**
     * 
     * @type {string}
     * @memberof ProfileUpdateEmail
     */
    'email'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProfileUpdateEmail
     */
    'id'?: number;
}
/**
 * 
 * @export
 * @interface ProfileUpdateEmailInputBody
 */
export interface ProfileUpdateEmailInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ProfileUpdateEmailInputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {ProfileUpdateEmail}
     * @memberof ProfileUpdateEmailInputBody
     */
    'object': ProfileUpdateEmail;
}
/**
 * 
 * @export
 * @interface ProfileUpdateEmailOutputBody
 */
export interface ProfileUpdateEmailOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ProfileUpdateEmailOutputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {Profile}
     * @memberof ProfileUpdateEmailOutputBody
     */
    'object': Profile;
}
/**
 * 
 * @export
 * @interface ProfileUpdateInputBody
 */
export interface ProfileUpdateInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ProfileUpdateInputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {ProfileUpdate}
     * @memberof ProfileUpdateInputBody
     */
    'object': ProfileUpdate;
}
/**
 * 
 * @export
 * @interface ProfileUpdateOutputBody
 */
export interface ProfileUpdateOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ProfileUpdateOutputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {Profile}
     * @memberof ProfileUpdateOutputBody
     */
    'object': Profile;
}
/**
 * 
 * @export
 * @interface SignInInputBody
 */
export interface SignInInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SignInInputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignInInputBody
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof SignInInputBody
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface SignInOutputBody
 */
export interface SignInOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SignInOutputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignInOutputBody
     */
    'token': string;
}
/**
 * 
 * @export
 * @interface SignUpInputBody
 */
export interface SignUpInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SignUpInputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpInputBody
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof SignUpInputBody
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface SignUpOutputBody
 */
export interface SignUpOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof SignUpOutputBody
     */
    '$schema'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpOutputBody
     */
    'token': string;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {SignInInputBody} signInInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signIn: async (signInInputBody: SignInInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signInInputBody' is not null or undefined
            assertParamExists('signIn', 'signInInputBody', signInInputBody)
            const localVarPath = `/auth/signin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SignUpInputBody} signUpInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp: async (signUpInputBody: SignUpInputBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signUpInputBody' is not null or undefined
            assertParamExists('signUp', 'signUpInputBody', signUpInputBody)
            const localVarPath = `/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {SignInInputBody} signInInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signIn(signInInputBody: SignInInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignInOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signIn(signInInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signIn']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SignUpInputBody} signUpInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUp(signUpInputBody: SignUpInputBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignUpOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUp(signUpInputBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {SignInInputBody} signInInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signIn(signInInputBody: SignInInputBody, options?: RawAxiosRequestConfig): AxiosPromise<SignInOutputBody> {
            return localVarFp.signIn(signInInputBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SignUpInputBody} signUpInputBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp(signUpInputBody: SignUpInputBody, options?: RawAxiosRequestConfig): AxiosPromise<SignUpOutputBody> {
            return localVarFp.signUp(signUpInputBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {SignInInputBody} signInInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signIn(signInInputBody: SignInInputBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signIn(signInInputBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SignUpInputBody} signUpInputBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signUp(signUpInputBody: SignUpInputBody, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signUp(signUpInputBody, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HomeApi - axios parameter creator
 * @export
 */
export const HomeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HomeApi - functional programming interface
 * @export
 */
export const HomeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HomeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async homeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HomeGetOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.homeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HomeApi.homeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HomeApi - factory interface
 * @export
 */
export const HomeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HomeApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        homeGet(options?: RawAxiosRequestConfig): AxiosPromise<HomeGetOutputBody> {
            return localVarFp.homeGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HomeApi - object-oriented interface
 * @export
 * @class HomeApi
 * @extends {BaseAPI}
 */
export class HomeApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HomeApi
     */
    public homeGet(options?: RawAxiosRequestConfig) {
        return HomeApiFp(this.configuration).homeGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileGet: async (authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ProfileUpdateInputBody} profileUpdateInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdate: async (profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profileUpdateInputBody' is not null or undefined
            assertParamExists('profileUpdate', 'profileUpdateInputBody', profileUpdateInputBody)
            const localVarPath = `/users/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profileUpdateInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdateEmail: async (profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profileUpdateEmailInputBody' is not null or undefined
            assertParamExists('profileUpdateEmail', 'profileUpdateEmailInputBody', profileUpdateEmailInputBody)
            const localVarPath = `/users/profile/email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profileUpdateEmailInputBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileGet(authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileGetOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileGet(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ProfileUpdateInputBody} profileUpdateInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileUpdate(profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileUpdateOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileUpdate(profileUpdateInputBody, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileUpdateEmail(profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileUpdateEmailOutputBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.profileUpdateEmail(profileUpdateEmailInputBody, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.profileUpdateEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileGet(authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileGetOutputBody> {
            return localVarFp.profileGet(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileUpdateInputBody} profileUpdateInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdate(profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileUpdateOutputBody> {
            return localVarFp.profileUpdate(profileUpdateInputBody, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
         * @param {string} [authorization] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileUpdateEmail(profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<ProfileUpdateEmailOutputBody> {
            return localVarFp.profileUpdateEmail(profileUpdateEmailInputBody, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public profileGet(authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileGet(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileUpdateInputBody} profileUpdateInputBody 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public profileUpdate(profileUpdateInputBody: ProfileUpdateInputBody, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileUpdate(profileUpdateInputBody, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProfileUpdateEmailInputBody} profileUpdateEmailInputBody 
     * @param {string} [authorization] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public profileUpdateEmail(profileUpdateEmailInputBody: ProfileUpdateEmailInputBody, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).profileUpdateEmail(profileUpdateEmailInputBody, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}



